### ISSUE TITLE
Pre-flight conversion checklist: Chapter 4, 2023

### ISSUE THREAD

**Issue by mpjashby** [mpjashby/crimemappingbook#1]
- [x] Copy over `images/` directory.
- [x] Add tutorial title as level-1 heading.
- [x] Add tutorial description as bold-face text after title.
- [x] Add instructions for opening corresponding tutorial.
- [x] Remove code from `setup` chunk that copies CSS files.
- [x] Remove exercise setup chunks and empty exercise chunks.
- [x] Remove quizzes.
- [x] Check for any references to `Run Code` button.
- [x] Convert pre-filled exercise chunks and exercise solution chunks to R code.
- [x] Convert video URLs to use the quarto shortcode `{{< video https://example.com/ab1sc >}}`.
- [x] Add reference to chapter file in top-level `_quarto.yml` file.
