### ISSUE TITLE
Pre-flight conversion checklist: Chapter 8, 2024

### ISSUE THREAD

**Issue by mpjashby** [mpjashby/crimemappingbook#12]
- [x] Copy over `images/` directory.
- [x] Add tutorial title as level-1 heading.
- [x] Add tutorial description as bold-face text after title.
- [x] Add instructions for opening corresponding tutorial:

````
::: {.box .load-tutorial}
To load the [interactive tutorial](../#how-to-use-this-book) for this chapter, copy and paste the following code into the RStudio console:

```r
crimemapping::tutorial("01_getting_started")
```

and press `Enter`.
:::
````

- [x] Remove YAML header.
- [x] Replace start of `setup` chunk with:

````r
```{r setup}
#| echo: false
#| include: false

source(here::here("mask_learnr_functions.R"))
```
````

- [x] Remove `library(learnr)` from `setup` chunk
- [x] Set `echo=FALSE` for any chunks with `-setup` in the chunk name.
- [x] Remove `section-` prefix from jquery code for extra-detail boxes.
- [x] Cmd+F for any references to `Run Code` button.
- [x] Convert video URLs to use the quarto shortcode `{{< video https://example.com/ab1sc >}}`.
- [x] Add reference to chapter file in top-level `_quarto.yml` file.
- [ ] Run `Build > Render Book`.
